Spree::PageContent.find_or_create_by! title: "Return Request for Order", description: "Lorem Ipsum is simply dummy text.", slug: "order-return-request-heading"
Spree::PageContent.find_or_create_by! title: "Return Qty", description: "", slug: "order-return-request-quantity"
Spree::PageContent.find_or_create_by! title: "Product Name", description: "", slug: "order-return-request-product-name"
Spree::PageContent.find_or_create_by! title: "Price Each", description: "", slug: "order-return-request-price-each"
Spree::PageContent.find_or_create_by! title: "Reason for Return", description: "", slug: "order-return-request-reason"
Spree::PageContent.find_or_create_by! title: "Preferred Resolution", description: "", slug: "order-return-request-resolution"
Spree::PageContent.find_or_create_by! title: "More Information Required", description: "", slug: "order-return-request-more-info"
Spree::PageContent.find_or_create_by! title: "Upload Images", description: "", slug: "order-return-request-price-upload-images"
Spree::PageContent.find_or_create_by! title: "Details of Return", description: "", slug: "order-return-request-detail"
Spree::PageContent.find_or_create_by! title: "Submit Request", description: "", slug: "order-return-request-submit-button-label"
